###
GET http://localhost:3001/api/users/profile/roles/get:1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzMzNzU2MjYzLCJleHAiOjE3MzM3NTk4NjN9.ZlHdQ6akhxSUoMqdaGjTptH0VREduZcuv5PBKd1mWHI