###
@env = dev

GET http://localhost:3001/api/users/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzMzNzUzNTEyLCJleHAiOjE3MzM3NTcxMTJ9.uyvNuwCpimym95ERhUZXYb4Qa6yIGAbQXx8EOhxlQ-o